### ISSUE TITLE
this repo's minor readme issue

### ISSUE THREAD

**Issue by TacheAlexandru** [PacktPublishing/Machine-Learning-for-Time-Series-with-Python#5]
Hi Ben!

Not a book issue, but one with the readme associated with this repo. The Key Features section starts fine but in the middle it accidentally switches into a description of [another Pack book](https://github.com/gdeckler/PowerBICookbook2ndEdition) on Power BI. Looking forward to reading your book!  

Alex

**Comment by benman1** [comment]
Hi @TacheAlexandru 
Thanks for pointing that out, much appreciated! I've just fixed that. 👍  Also, many thanks for the interest in my book. Please let me know if you have any more feedback.
